# Based on:
# https://github.com/opentofu/setup-opentofu
# https://cd.foundation/blog/2024/02/28/how-to-deploy-infrastructure-in-ci-cd-using-opentofu/

# When we create a pull request (PR) to the main branch, this workflow runs `tofu plan`, and adds the output as a comment to the PR. If the plan looks good, we merge (ie. push) the code to the main branch. On push to main, this runs a `tofu apply`.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  id-token: write
  contents: read
  pull-requests: write

# Secrets are in https://github.com/Equal-Vote/terraform/settings/secrets/actions
env:
  ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
  ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}

jobs:
  opentofu:
    runs-on: ubuntu-latest
    # env:
    #   #this is needed since we are running terraform with read-only permissions
    #   ARM_SKIP_PROVIDER_REGISTRATION: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: opentofu/setup-opentofu@fc711fa910b93cba0f3fbecaafc9f42fd0c411cb # v2.0.0
        with:
          # Prefer `tofu_version_file` over `tofu_version`, because the version file ensures that both local and workflow runs are locked to the same version.
          tofu_version_file: .opentofu-version
      # https://github.com/magnetikonline/terraform-github-action-cache-example
      - name: Configure Terraform plugin cache
        run: |
          echo "TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache" >>"$GITHUB_ENV"
          mkdir --parents "$HOME/.terraform.d/plugin-cache"
      - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-
      - id: fmt
        run: tofu fmt -recursive -check
        continue-on-error: true
      - id: init
        run: tofu init
      - id: validate
        run: tofu validate -no-color
      - id: plan
        run: tofu plan -no-color -input=false -out=plan.file
        # We need to continue-on-error here so we can print the tofu plan output even on failure.
        continue-on-error: true
      - run: |
          echo "${{ steps.plan.outputs.stdout }}" > plan-output.txt
          echo "${{ steps.plan.outputs.stderr }}" >> plan-output.txt
        if: github.event_name == 'pull_request'
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: "const fs = require('fs'); const planOutput = fs.readFileSync('plan-output.txt', 'utf8'); const output = `#### OpenTofu Format and Style \\`${{ steps.fmt.outcome }}\\`\\n#### OpenTofu Initialization ⚙️\\`${{ steps.init.outcome }}\\`\\n#### OpenTofu Validation \\`${{ steps.validate.outcome }}\\`\\n<details><summary>Validation Output</summary>\\n\\n\\`\\`\\`\\n\\n${{ steps.validate.outputs.stdout }}\\n\\`\\`\\`\\n\\n</details>\\n\\n#### OpenTofu Plan \\`${{ steps.plan.outcome }}\\`\\n\\n<details><summary>Show Plan</summary>\\n\\n\\`\\`\\`\\n\\n${planOutput}\\n\\`\\`\\`\\n\\n</details>\\n\\n*Pusher: @${{ github.actor }}, Action: \\`${{ github.event_name }}\\`, Working Directory: \\`${{ env.tf_actions_working_dir }}\\`, Workflow: \\`${{ github.workflow }}\\`*`; github.rest.issues.createComment({ issue_number: context.issue.number, owner: context.repo.owner, repo: context.repo.repo, body: output })"
      # We need the workflow to show as failed when the plan fails, so we're breaking it here.
      - name: Check plan result
        if: steps.plan.outcome == 'failure'
        run: exit 1
      - if: github.ref == 'refs/heads/main'
        run: tofu apply -no-color -input=false plan.file
